#Introduction to Pandas

In [1]:
import pandas as pd

In [2]:
pd.Series([1, 2, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [3]:
df = pd.DataFrame({"names":["Harry", "Rohan", "Subham"], "marks":[100,35,55]})

In [4]:
df

    names  marks
0   Harry    100
1   Rohan     35
2  Subham     55

In [5]:
dff = pd.read_csv("iris-write-from-docker.csv")

In [6]:
dff

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           NaN          0.2     Iris-setosa
2             4.7          NaN           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
dff.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           NaN          0.2  Iris-setosa
2           4.7          NaN           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
dff.tail()

     sepal_length  sepal_width  petal_length  petal_width           class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [9]:
dff.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000    149.00000    148.000000   149.000000
mean       5.843333      3.05302      3.789865     1.206040
std        0.828066      0.43489      1.755564     0.760354
min        4.300000      2.00000      1.000000     0.100000
25%        5.100000      2.80000      1.600000     0.300000
50%        5.800000      3.00000      4.400000     1.300000
75%        6.400000      3.30000      5.100000     1.800000
max        7.900000      4.40000      6.900000     2.500000

In [10]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  148 non-null    float64
 3   petal_width   149 non-null    float64
 4   class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

##Data Selection

In [11]:
dff["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [12]:
type(dff["sepal_length"])

pandas.core.series.Series

In [13]:
dff[["sepal_length","petal_length"]]

     sepal_length  petal_length
0             5.1           1.4
1             4.9           NaN
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [14]:
dff.iloc[0]

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 0, dtype: object

In [15]:
ind = pd.read_csv("industry2.csv")

In [16]:
ind

                        Industry
0             Accounting/Finance
1   Advertising/Public Relations
2             Aerospace/Aviation
3               Banking/Mortgage
4           Business Development
5        Clerical/Administrative
6        Construction/Facilities
7                 Consumer Goods
8               Customer Service
9             Education/Training
10              Energy/Utilities
11                   Engineering
12           Government/Military
13                         Green
14                    Healthcare
15            Hospitality/Travel
16               Human Resources
17      Installation/Maintenance
18                     Insurance
19                      Internet
20               Job Search Aids
21      Law Enforcement/Security
22                         Legal
23          Management/Executive
24      Manufacturing/Operations
25                     Marketing
26          Non-Profit/Volunteer
27        Pharmaceutical/Biotech
28         Professional Services
29            QA/Quality Control
30                   Real Estate
31       Restaurant/Food Service
32                        Retail
33                         Sales
34              Science/Research
35                 Skilled Labor
36                    Technology
37            Telecommunications
38      Transportation/Logistics
39                         Other

In [17]:
iris = pd.read_csv("iris.csv")

In [18]:
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           NaN          0.2     Iris-setosa
2             4.7          NaN           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [19]:
iris.dropna()

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[146 rows x 5 columns]

In [20]:
iris.fillna(5)

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           5.0          0.2     Iris-setosa
2             4.7          5.0           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [21]:
iris.rename(columns={"sepal_length":"sl"})

      sl  sepal_width  petal_length  petal_width           class
0    5.1          3.5           1.4          0.2     Iris-setosa
1    4.9          3.0           NaN          0.2     Iris-setosa
2    4.7          NaN           1.3          0.2     Iris-setosa
3    4.6          3.1           1.5          0.2     Iris-setosa
4    5.0          3.6           1.4          0.2     Iris-setosa
..   ...          ...           ...          ...             ...
145  6.7          3.0           5.2          2.3  Iris-virginica
146  6.3          2.5           5.0          1.9  Iris-virginica
147  6.5          3.0           5.2          2.0  Iris-virginica
148  6.2          3.4           5.4          2.3  Iris-virginica
149  5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [22]:
iris['sepal_length']= iris['sepal_length'].astype(int)

In [23]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    int64
 1   sepal_width   149 non-null    float64
 2   petal_length  148 non-null    float64
 3   petal_width   149 non-null    float64
 4   class         150 non-null    object
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB

In [27]:
iris['sepal_width']= iris['sepal_width'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [28]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  148 non-null    float64
 3   petal_width   149 non-null    float64
 4   class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [31]:
iris["zeroes"] = [i for i in range(len(iris))]

In [32]:
iris

,sepal_length,sepal_width,petal_length,petal_width,class,zeroes
0,5,3.5,1.4,0.2,Iris-setosa,0
1,4,3.0,NaN,0.2,Iris-setosa,1
2,4,NaN,1.3,0.2,Iris-setosa,2
3,4,3.1,1.5,0.2,Iris-setosa,3
4,5,3.6,1.4,0.2,Iris-setosa,4
...,...,...,...,...,...,...
145,6,3.0,5.2,2.3,Iris-virginica,145
146,6,2.5,5.0,1.9,Iris-virginica,146
147,6,3.0,5.2,2.0,Iris-virginica,147
148,6,3.4,5.4,2.3,Iris-virginica,148
149,5,3.0,5.1,1.8,Iris-virginica,149

In [ ]:
iris["zeroes"] = [i for i in range(len(iris))]

In [ ]:
iris

In [ ]:
def fx(a):
    return a+1
iris['ones'] = iris['sepal_length'].apply(fx)

In [ ]:
iris

In [33]:
iris.to_csv("export.csv", index = False)

In [ ]:
df1 = pd.DataFrame({"names":["Harry", "Rohan", "Subham"], 
                    "marks":[100,35,55]})

In [ ]:
df1

In [34]:
df2 = pd.DataFrame({"names":["Anik", "Kiran", "Ayan"], 
                    "marks":[59,32,89]})

In [35]:
df2

   names  marks
0   Anik     59
1  Kiran     32
2   Ayan     89

In [36]:
pd.concat([df1, df2])

NameError: name 'df1' is not defined

In [ ]:
df3 = pd.DataFrame({"names":["Anik", "Kiran", "Ayan"], 
                    "marks":[59,3,89]})

In [ ]:
df3

In [ ]:
df4 = pd.DataFrame({"names":["Anik", "Kiran", "Ayan"], 
                    "roll":[122,355,459]})

In [ ]:
df4

In [ ]:
pd.merge(df3,df4,on="names")